version: 2
jobs:
   build:
     docker:
       - image: lukaszkostka/avr:debian_stretch
     steps:
       - checkout
       - run:
          name: Run cmake
          environment:
            CC: avr-gcc
            CXX: avr-g++
          command: >
            cmake
            -DBAUD=115200
            -DF_CPU=11059200
            -H.
            -GNinja
            -Bbuild
       - run:
          name: Build
          command: ninja -C build
