version: 2
jobs:
   build:
     docker:
       - image: lukaszkostka/devbox:stretch
     steps:
       - checkout
       - run:
          name: Run cmake
          command: |
            cd build
            cmake -DBAUD=115200 -DF_CPU=11059200 ..
       - run:
          name: Build
          command: |
            cd build
            make -j
