version: 2
jobs:
   build:
     docker:
       - image: lukaszkostka/avr:alpine_3.9
     steps:
       - checkout
       - run:
          name: Run cmake
          environment:
            CMAKE_BUILD_TYPE: MinSizeRel
            CC: avr-gcc
            CXX: avr-g++
          command: >
            cmake
            -H.
            -GNinja
            -Bbuild
       - run:
          name: Build
          command: ninja -C build
       - run:
          name: Size
          command: ninja -C build size
