name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lukaszkostka/avr:debian_buster
    strategy:
      matrix:
        mcu:
          - atmega32
          - atmega2560
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run meson
        run: >
          meson
          .
          build
          --cross-file ${{ matrix.mcu }}.conf
          --buildtype=minsize
      - name: Build
        run: ninja -C build
  test:
    runs-on: ubuntu-latest
    container:
      image: lukaszkostka/avr:debian_buster
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run meson
        run: >
          meson
          .
          build
      - name: Build
        run: ninja -C build tests
      - name: Run tests
        run: build/tests
