name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lukaszkostka/avr:alpine_3.9
      env:
        CXX: avr-g++
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run cmake
        run: >
          cmake
          -DF_CPU=11059200
          -DCMAKE_BUILD_TYPE=MinSizeRel
          -DMCU=atmega32
          -H.
          -GNinja
          -Bbuild
      - name: Build
        run: ninja -C build
      - name: Size
        run: ninja -C build size
